-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 17:09:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uveats` DEFAULT CHARACTER SET utf8 ;
USE `uveats` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(80) NOT NULL,
  `apellidoPaterno` NVARCHAR(80) NULL,
  `apellidoMaterno` NVARCHAR(80) NULL,
  `correo` NVARCHAR(100) NOT NULL,
  `contrasenia` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` NVARCHAR(80) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comida` (
  `idComida` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(100) NOT NULL,
  `precio` DECIMAL(5,2) NOT NULL,
  `descripcion` NVARCHAR(200) NOT NULL,
  `imagen` LONGBLOB NOT NULL,
  PRIMARY KEY (`idComida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_tipo_usuario` (
  `idUsuarioTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `tipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarioTipoUsuario`),
  INDEX `fk_usuario_has_tipo_usuario_tipo_usuario1_idx` (`tipoUsuario` ASC),
  INDEX `fk_usuario_has_tipo_usuario_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario_has_tipo_usuario_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_tipo_usuario_tipo_usuario1`
    FOREIGN KEY (`tipoUsuario`)
    REFERENCES `mydb`.`tipo_usuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`establecimiento` (
  `idEstablecimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(100) NOT NULL,
  `categoria` NVARCHAR(100) NOT NULL,
  `codigoPostal` NVARCHAR(5) NOT NULL,
  `numero` INT NOT NULL,
  `calle` NVARCHAR(100) NOT NULL,
  `pais` NVARCHAR(100) NOT NULL,
  `ciudad` NVARCHAR(100) NOT NULL,
  `estado` NVARCHAR(100) NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`idEstablecimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comida_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comida_establecimiento` (
  `idComidaEstablecimiento` INT NOT NULL AUTO_INCREMENT,
  `comida` INT NOT NULL,
  `establecimiento` INT NOT NULL,
  PRIMARY KEY (`idComidaEstablecimiento`),
  INDEX `fk_comida_has_establecimiento_establecimiento1_idx` (`establecimiento` ASC),
  INDEX `fk_comida_has_establecimiento_comida1_idx` (`comida` ASC),
  CONSTRAINT `fk_comida_has_establecimiento_comida1`
    FOREIGN KEY (`comida`)
    REFERENCES `mydb`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_has_establecimiento_establecimiento1`
    FOREIGN KEY (`establecimiento`)
    REFERENCES `mydb`.`establecimiento` (`idEstablecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `precioTotal` DECIMAL(5,2) NOT NULL,
  `estado` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `fk_carrito_estado1_idx` (`estado` ASC),
  INDEX `fk_carrito_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_carrito_estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificacion` (
  `idCalificacion` INT NOT NULL AUTO_INCREMENT,
  `comentario` NVARCHAR(500) NULL,
  `puntaje` INT NOT NULL,
  `comida` INT NOT NULL,
  PRIMARY KEY (`idCalificacion`),
  INDEX `fk_calificacion_comida1_idx` (`comida` ASC),
  CONSTRAINT `fk_calificacion_comida1`
    FOREIGN KEY (`comida`)
    REFERENCES `mydb`.`comida` (`idComida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `comidaEstablecimiento` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `carrito` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_usuario_has_comida_establecimiento_comida_establecimient_idx` (`comidaEstablecimiento` ASC),
  INDEX `fk_pedido_carrito1_idx` (`carrito` ASC),
  CONSTRAINT `fk_usuario_has_comida_establecimiento_comida_establecimiento1`
    FOREIGN KEY (`comidaEstablecimiento`)
    REFERENCES `mydb`.`comida_establecimiento` (`idComidaEstablecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_carrito1`
    FOREIGN KEY (`carrito`)
    REFERENCES `mydb`.`carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
